name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up PHP environment
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Cambia según la versión de PHP que uses
        coverage: pcov # Incluye soporte para pruebas de cobertura

    # 3. Install dependencies using Composer
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # 4. Run migrations (si tu aplicación requiere una base de datos para las pruebas)
    - name: Prepare the database
      run: |
        php artisan migrate --database=sqlite --force

    # 5. Run tests
    - name: Run PHPUnit tests
      run: ./vendor/bin/pest

    # 6. Optional: Generate code coverage report
    - name: Generate code coverage
      run: |
        php -d pcov.enabled=1 ./vendor/bin/pest --coverage-html coverage
      if: always() # Siempre genera el reporte